steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/key-charmer-444222-i1/buylist','--build-arg=JAR_FILE=target/buylist', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/key-charmer-444222-i1/buylist' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'buylist', '--image', 'gcr.io/key-charmer-444222-i1/buylist', '--region', 'europe-west6' ]
    env:
      - 'TOKEN_TG=$TOKEN_TG'
      - 'TOKEN_TODOIST=$TOKEN_TODOIST'
images:
  - gcr.io/key-charmer-444222-i1/buylist

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 'projects/key-charmer-444222-i1/serviceAccounts/339598143858-compute@developer.gserviceaccount.com'