[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# baylist

## полезные ссылки

### хостинг

#### https://free\-for\.dev/\#/?id=dbaas

#### https://gist\.github\.com/bmaupin/d2d243218863320b01b0c1e1ca0cf5f3

#### https://gist\.github\.com/bmaupin/0ce79806467804fdbbf8761970511b8c

## бд

### внешние

#### sql

##### db\.bit\.io\(postgresql\)
- NOTE
<pre>https://bit.io/mess9

postgresql://mess9:v2_43cHM_rTuNRTM35KVXTqZBEfqxkZm@db.bit.io:5432/mess9/baylist

dbname=mess9/baylist
username=mess9
host=db.bit.io
port=5432
pass=v2_43cHz_5PALtdmJrrGAE4e4zzsc4Lj

limit 3gb</pre>

#### nosql

##### mongo atlas
- NOTE
<pre>https://cloud.mongodb.com/v2/64442d94517c765d99f3689a#/clusters

--если не резолвить днс
mongodb://&lt;username&gt;:&lt;password&gt;@ac-brl9kus-shard-00-00.mgdagze.mongodb.net:27017,ac-brl9kus-shard-00-01.mgdagze.mongodb.net:27017,ac-brl9kus-shard-00-02.mgdagze.mongodb.net:27017/?ssl=true&amp;replicaSet=atlas-2scpt2-shard-0&amp;authSource=admin&amp;retryWrites=true&amp;w=majority

-- если с днс всё в порядке
mongodb+srv://&lt;username&gt;:&lt;password&gt;@mess9.mgdagze.mongodb.net/?retryWrites=true&amp;w=majority

username=mess9
pass=654654

можно добавить ещё юзеров

лимит 512 мб

</pre>
