### log ###
logging:
  level:
    org.baylist.api.TodoistFeignClient: debug
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
    root: info
#    com.zaxxer.hikari: DEBUG
#    oracle.jdbc: DEBUG

### connect ###
todoist:
  baseUrl: https://api.todoist.com/rest/v2
spring:
  ai:
    openai:
      api-key: ${OPENAI_TOKEN}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
  #  ai:
  #    openai:
  #      base-url: https://api.deepseek.com
  #      api-key: ${DS_TOKEN}
  #      chat:
  #        enabled: true
  #        options:
  #          model: deepseek-chat
  #          temperature: 0.7
  #      embedding:
  #        enabled: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:oracle:thin:@db1_high
    username: BUYLIST
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.OracleDialect
  cloud:
    openfeign:
      client:
        config:
          todoistClient:
            loggerLevel: full

### deploy ###
management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8080
  address: 0.0.0.0

