### log ###
logging:
  level:
    org.baylist.api.TodoistFeignClient: debug
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
    root: info
#    com.zaxxer.hikari: DEBUG
#    oracle.jdbc: DEBUG

### connect ###
todoist:
  baseUrl: https://api.todoist.com/rest/v2
spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://152.70.174.74:5432/buylist
    username: buylist
    password: ${POSTGRES_DB_PASSWORD}

  cloud:
    openfeign:
      client:
        config:
          todoistClient:
            loggerLevel: full

### deploy ###
management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8080
  address: 0.0.0.0

jwt:
  secret: ${JWT_SECRET:49cc56846dbc00e7d2d1022821833fe138489cdd42dabb0eccd963db710b4dff}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

telegram:
  bot:
    token: ${TOKEN_TG}

