name: Maven Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          java-package: jdk
          architecture: x64
          check-latest: false
          overwrite-settings: true

      - name: Build with Maven
        run: mvn package -DskipTests=true -f pom.xml

      - name: Upload JAR as an artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: buylist.jar
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Запускаем деплой только после успешной сборки

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            export gpt=${{ secrets.GPT }}
            export OPENAI_TOKEN=${{ secrets.OPENAI_TOKEN }}
            export ORACLE_DB_PASSWORD=${{ secrets.ORACLE_DB_PASSWORD }}
            export TNS_ADMIN=${{ secrets.TNS_ADMIN }}
            export TOKEN_TG=${{ secrets.TOKEN_TG }}
            cd /home/ubuntu/deploy
            scp target/*.jar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/ubuntu/deploy/
            java -jar /home/ubuntu/deploy/baylist-0.0.7.jar

